name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  # Manually trigger workflow

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build (Linux)
      run: cargo build --verbose
    - name: Run tests (Linux)
      run: cargo test --verbose

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust (Windows)
      uses: dtolnay/rust-toolchain@stable
    - name: Build (Windows)
      run: cargo build --verbose
    - name: Run tests (Windows)
      run: cargo test --verbose

  build-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust (macOS)
      uses: dtolnay/rust-toolchain@stable
    - name: Build (macOS)
      run: cargo build --verbose
    - name: Run tests (macOS)
      run: cargo test --verbose