name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  # Manually trigger workflow

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build (Linux)
      run: cargo build --release --verbose
    - name: Run tests (Linux)
      run: cargo test --verbose
    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-artifact
        path: target/release/ipd-simulator

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust (Windows)
      uses: dtolnay/rust-toolchain@stable
    - name: Build (Windows)
      run: cargo build --release --verbose
    - name: Run tests (Windows)
      run: cargo test --verbose
    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-artifact
        path: target/release/ipd-simulator.exe

  build-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust (macOS)
      uses: dtolnay/rust-toolchain@stable
    - name: Build (macOS)
      run: cargo build --release --verbose
    - name: Run tests (macOS)
      run: cargo test --verbose
    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-artifact
        path: target/release/ipd-simulator
